#!/usr/bin/env python3
"""Generate ``crates/metrics/prices.json`` from Anthropic's published pricing table.

The table was hand-maintained and went stale twice (ADR-0022's Opus-3 rates,
then cadence-hooks#865's $0 models and 5-minute cache-write rates). This script
makes it generated (cadence-hooks#866). Three modes:

``--check``
    Offline, run at PR time. Validates the committed file (slugs, five rates
    per row, every rate in ``0 < r <= 1000``) and that it is byte-identical to
    this script's canonical rendering of it. Never touches the network, so a
    pull request never depends on a third-party site's uptime.

``--refresh``
    Network, run by the weekly ``prices.yml`` job. Fetches the markdown page,
    parses the ``## Model pricing`` table, and rewrites the file. ``--page FILE``
    parses a saved copy instead, which is how the tests and a local dry run
    work without a fetch.

``--format``
    Offline. Rewrites the committed file into canonical form after a hand edit.

What it refuses to do, each from the #866 review panel:

* Accept a page whose rates are non-finite, zero, or above 1000 per MTok. An
  all-``$0.00`` page parses cleanly otherwise and would silently zero the
  ledger.
* Move any committed rate by more than 10x in one run. A real repricing inside
  that bound only earns a ``NOTE:`` about multiplier drift, never a block.
* Drop a committed model the page no longer lists, unless ``--allow-removals``
  is given; then the committed row is KEPT (old transcripts still price against
  it) and a ``NOTE:`` names it. Without the flag the weekly job would wedge
  forever, because retired rows do leave the page.
* Follow a redirect to anything but ``https`` on an allowlisted host, read more
  than 2 MiB, or wait more than 30 seconds.
* Print page content. Stdout, stderr, and ``--body-file`` carry only validated
  slugs and numbers; the body file becomes a public PR description, and log
  masking does not cover PR bodies. A fetch failure prints the exception's
  class name, never its repr.

``lastVerified`` moves only when a rate actually changes, so an unchanged week
produces no diff at all.
"""

from __future__ import annotations

import argparse
import datetime
import email.message
import json
import math
import re
import ssl
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

SOURCE_URL = "https://platform.claude.com/docs/en/about-claude/pricing.md"
ALLOWED_HOSTS = frozenset({"platform.claude.com", "docs.claude.com", "docs.anthropic.com"})
MAX_BYTES = 2 * 1024 * 1024
TIMEOUT_SECONDS = 30
DEFAULT_PRICES = Path(__file__).resolve().parent.parent / "crates" / "metrics" / "prices.json"

# Header equality, not a substring match: the batch, fast-mode, and tool-token
# tables also start with a `Model` column.
HEADER = [
    "Model",
    "Base input tokens",
    "5m cache writes",
    "1h cache writes",
    "Cache hits and refreshes",
    "Output tokens",
]
# Row keys in column order, and in the order they are written.
COLUMN_KEYS = [
    "inputPerMTok",
    "cacheWritePerMTok",
    "cacheWrite1hPerMTok",
    "cacheReadPerMTok",
    "outputPerMTok",
]
WRITE_ORDER = [
    "inputPerMTok",
    "outputPerMTok",
    "cacheWritePerMTok",
    "cacheWrite1hPerMTok",
    "cacheReadPerMTok",
]
# Published multipliers over base input. Used ONLY to annotate drift; no rate
# is ever derived from them (Fable 5.1's cache read is 0.025x, not 0.1x).
MULTIPLIERS = {
    "cacheWritePerMTok": 1.25,
    "cacheWrite1hPerMTok": 2.0,
    "cacheReadPerMTok": 0.1,
}
SLUG_RE = re.compile(r"^claude-[a-z]+-[0-9]+(-[0-9]+)?$")
NAME_RE = re.compile(r"^Claude ([A-Z][a-z]+) ([0-9]+(?:\.[0-9]+)?)$")
RATE_RE = re.compile(r"^\$([0-9]+(?:\.[0-9]+)?) / MTok$")
SUP_RE = re.compile(r"<sup>.*?</sup>")
SEPARATOR_CELL_RE = re.compile(r"^:?-+:?$")
MAX_RATE = 1000.0
MAX_MOVE = 10.0

NOTES = (
    "Generated by scripts/generate-prices.py from the published pricing table "
    "(cadence-hooks#866); run --format after any hand edit, or CI's --check "
    "fails. All prices in USD per million tokens, read from the table rather "
    "than derived: claude-fable-5-1 and claude-mythos-5-1 bill cache reads at "
    "0.025x input and claude-opus-5-5 at 0.05x, not the usual 0.1x. "
    "claude-opus-4 and claude-sonnet-4 are slugged from the table's display "
    "names; the published API aliases are claude-opus-4-0 and "
    "claude-sonnet-4-0, and dated ids such as claude-opus-4-20250514 still "
    "resolve to these rows through the dated-suffix lookup. Fast mode "
    "(speed: fast) bills at a premium this table does not model: claude-opus-5 "
    "and claude-opus-4-8 at $10/$50 input/output, claude-opus-5-5 at $8/$40. "
    "lastVerified moves only when a rate changes."
)


class PricingError(Exception):
    """A validation failure. The message carries only slugs and numbers."""


# --- parsing -----------------------------------------------------------------


def _cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def slugify(display_name: str) -> str:
    """``Claude Opus 4.1 ([retired…](…))`` -> ``claude-opus-4-1``."""
    name = SUP_RE.sub("", display_name)
    name = name.split(" (", 1)[0].strip()
    match = NAME_RE.match(name)
    if not match:
        raise PricingError("a model-pricing row has an unrecognized model name")
    family, version = match.groups()
    slug = f"claude-{family.lower()}-{version.replace('.', '-')}"
    if not SLUG_RE.match(slug):
        raise PricingError("a model-pricing row slugged to an invalid id")
    return slug


def parse_rate(cell: str, slug: str) -> float:
    match = RATE_RE.match(SUP_RE.sub("", cell).strip())
    if not match:
        raise PricingError(f"{slug}: a rate cell is not in `$N / MTok` form")
    return check_rate(float(match.group(1)), slug)


def check_rate(rate: object, slug: str) -> float:
    if isinstance(rate, bool) or not isinstance(rate, (int, float)):
        raise PricingError(f"{slug}: a rate is not a number")
    rate = float(rate)
    if not math.isfinite(rate) or not 0 < rate <= MAX_RATE:
        raise PricingError(f"{slug}: rate {rate!r} is outside 0 < r <= {MAX_RATE:g}")
    return rate


def parse_table(markdown: str) -> dict[str, dict[str, float]]:
    """Parse the ``## Model pricing`` table into ``{slug: {key: rate}}``."""
    lines = markdown.splitlines()
    anchors = [i for i, line in enumerate(lines) if "Base input tokens" in line]
    if len(anchors) != 1:
        raise PricingError(
            f"expected exactly one line containing `Base input tokens`, found {len(anchors)}"
        )
    start = anchors[0]
    if _cells(lines[start]) != HEADER:
        raise PricingError("the model-pricing header does not match the expected columns")
    if start + 1 >= len(lines) or not all(
        SEPARATOR_CELL_RE.match(cell) for cell in _cells(lines[start + 1])
    ):
        raise PricingError("the model-pricing header is not followed by a separator row")

    models: dict[str, dict[str, float]] = {}
    for line in lines[start + 2 :]:
        if not line.lstrip().startswith("|"):
            break
        cells = _cells(line)
        if len(cells) != len(HEADER):
            raise PricingError("a model-pricing row has the wrong number of cells")
        slug = slugify(cells[0])
        if slug in models:
            raise PricingError(f"{slug}: listed twice")
        models[slug] = {key: parse_rate(cell, slug) for key, cell in zip(COLUMN_KEYS, cells[1:])}
    if not models:
        raise PricingError("the model-pricing table has no rows")
    return models


def validate_models(models: object) -> dict[str, dict[str, float]]:
    """Validate a committed ``models`` object the way a parsed page is validated."""
    if not isinstance(models, dict) or not models:
        raise PricingError("`models` must be a non-empty object")
    out: dict[str, dict[str, float]] = {}
    for slug, row in models.items():
        if not isinstance(slug, str) or not SLUG_RE.match(slug):
            raise PricingError("a committed model id does not match the slug pattern")
        if not isinstance(row, dict) or set(row) != set(COLUMN_KEYS):
            raise PricingError(f"{slug}: must carry exactly the five rate keys")
        out[slug] = {key: check_rate(row[key], slug) for key in COLUMN_KEYS}
    return out


# --- rendering ---------------------------------------------------------------


def format_rate(rate: float) -> str:
    """Two decimals, or as many as the rate needs (``0.025``)."""
    fixed = f"{rate:.2f}"
    return fixed if float(fixed) == rate else repr(rate)


def render(meta: dict[str, str], models: dict[str, dict[str, float]]) -> str:
    """Canonical text: `_meta` keys in a fixed order, models sorted by id."""
    out = ["{", '  "_meta": {']
    meta_keys = ["lastVerified", "source", "notes"]
    for i, key in enumerate(meta_keys):
        comma = "," if i < len(meta_keys) - 1 else ""
        out.append(f"    {json.dumps(key)}: {json.dumps(meta[key])}{comma}")
    out += ["  },", '  "models": {']
    slugs = sorted(models)
    for i, slug in enumerate(slugs):
        out.append(f"    {json.dumps(slug)}: {{")
        for j, key in enumerate(WRITE_ORDER):
            comma = "," if j < len(WRITE_ORDER) - 1 else ""
            out.append(f"      {json.dumps(key)}: {format_rate(models[slug][key])}{comma}")
        out.append("    }" + ("," if i < len(slugs) - 1 else ""))
    out += ["  }", "}"]
    return "\n".join(out) + "\n"


# --- refresh -----------------------------------------------------------------


def refresh(
    committed: dict,
    page_models: dict[str, dict[str, float]],
    *,
    allow_removals: bool,
    today: str,
) -> tuple[dict[str, str], dict[str, dict[str, float]], list[str], list[str]]:
    """Merge the parsed page over the committed table.

    Returns ``(meta, models, changes, notes)``. Raises on a >10x move, or on a
    removal without ``allow_removals``.
    """
    old = validate_models(committed.get("models"))
    notes: list[str] = []
    changes: list[str] = []

    for slug in sorted(set(old) - set(page_models)):
        if not allow_removals:
            raise PricingError(
                f"{slug}: committed but absent from the published table (pass --allow-removals to keep it)"
            )
        notes.append(f"{slug} is no longer listed; its committed row is kept.")

    for slug in sorted(set(old) & set(page_models)):
        for key in COLUMN_KEYS:
            before, after = old[slug][key], page_models[slug][key]
            if max(before, after) / min(before, after) > MAX_MOVE:
                raise PricingError(
                    f"{slug}: {key} moved {format_rate(before)} -> {format_rate(after)}, more than {MAX_MOVE:g}x"
                )
            if before != after:
                changes.append(f"{slug} {key}: {format_rate(before)} -> {format_rate(after)}")

    for slug in sorted(set(page_models) - set(old)):
        rates = page_models[slug]
        changes.append(
            f"{slug} added: " + ", ".join(f"{key} {format_rate(rates[key])}" for key in WRITE_ORDER)
        )

    for slug in sorted(page_models):
        rates = page_models[slug]
        for key, multiplier in MULTIPLIERS.items():
            expected = rates["inputPerMTok"] * multiplier
            if not math.isclose(rates[key], expected, rel_tol=1e-9, abs_tol=1e-9):
                notes.append(
                    f"{slug} {key} is {format_rate(rates[key])}, not the {multiplier:g}x "
                    f"multiplier ({format_rate(round(expected, 6))}); the published rate is used."
                )

    models = {**old, **page_models}
    old_meta = committed.get("_meta") or {}
    last_verified = old_meta.get("lastVerified")
    if models != old or not isinstance(last_verified, str):
        last_verified = today
    meta = {"lastVerified": last_verified, "source": SOURCE_URL, "notes": NOTES}
    return meta, models, changes, notes


def body_markdown(changes: list[str], notes: list[str], reordered: bool) -> str:
    """PR body built only from validated slugs and numbers."""
    lines = [
        "Weekly regeneration of `crates/metrics/prices.json` from the published pricing table "
        f"(`{SOURCE_URL}`), by `scripts/generate-prices.py --refresh` (cadence-hooks#866).",
        "",
        "## Rate changes",
        "",
    ]
    lines += [f"- {change}" for change in changes] or ["- none"]
    if notes:
        lines += ["", "## Notes", ""] + [f"- NOTE: {note}" for note in notes]
    if reordered:
        lines += [
            "",
            "The committed file was not in canonical form, so this diff also reorders keys "
            "(models sorted by id). That part is not a price change.",
        ]
    return "\n".join(lines) + "\n"


# --- fetch -------------------------------------------------------------------


def assert_allowed_url(url: str) -> None:
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme != "https" or parsed.hostname not in ALLOWED_HOSTS:
        raise PricingError("the pricing URL left https on an allowlisted host")


def media_type(content_type: str | None) -> str:
    """The bare media type of a Content-Type value (parameters dropped)."""
    message = email.message.Message()
    message["Content-Type"] = content_type or ""
    return message.get_content_type()


class _AllowlistRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: D102
        assert_allowed_url(newurl)
        return super().redirect_request(req, fp, code, msg, headers, newurl)


def fetch(url: str = SOURCE_URL) -> str:
    assert_allowed_url(url)
    opener = urllib.request.build_opener(
        urllib.request.HTTPSHandler(context=ssl.create_default_context()),
        _AllowlistRedirect(),
    )
    request = urllib.request.Request(url, headers={"User-Agent": "cadence-hooks-prices/1"})
    try:
        with opener.open(request, timeout=TIMEOUT_SECONDS) as response:
            assert_allowed_url(response.geturl())
            if media_type(response.headers.get("Content-Type")) != "text/markdown":
                raise PricingError("the pricing page is not served as text/markdown")
            body = response.read(MAX_BYTES + 1)
            charset = response.headers.get_content_charset() or "utf-8"
    except PricingError:
        raise
    except (urllib.error.URLError, OSError, ValueError) as exc:
        raise PricingError(f"fetch failed ({type(exc).__name__})") from None
    if len(body) > MAX_BYTES:
        raise PricingError(f"the pricing page exceeds {MAX_BYTES} bytes")
    try:
        return body.decode(charset)
    except (LookupError, UnicodeDecodeError):
        raise PricingError("the pricing page could not be decoded") from None


# --- CLI ---------------------------------------------------------------------


def load_committed(path: Path) -> tuple[str, dict]:
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        raise PricingError(f"{path.name} is not valid JSON") from None
    if not isinstance(data, dict):
        raise PricingError(f"{path.name} must be a JSON object")
    return text, data


def canonical_text(data: dict) -> str:
    meta = data.get("_meta")
    if not isinstance(meta, dict) or not all(
        isinstance(meta.get(key), str) for key in ("lastVerified", "source", "notes")
    ):
        raise PricingError("`_meta` must carry string lastVerified, source, and notes")
    return render(meta, validate_models(data.get("models")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="validate offline (CI)")
    mode.add_argument("--refresh", action="store_true", help="regenerate from the pricing page")
    mode.add_argument("--format", action="store_true", help="rewrite in canonical form")
    parser.add_argument("--prices", type=Path, default=DEFAULT_PRICES)
    parser.add_argument("--page", type=Path, help="parse a saved page instead of fetching")
    parser.add_argument("--allow-removals", action="store_true")
    parser.add_argument("--body-file", type=Path, help="write a PR body (refresh only)")
    parser.add_argument("--today", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    try:
        text, data = load_committed(args.prices)
        if args.check:
            if canonical_text(data) != text:
                raise PricingError(
                    f"{args.prices.name} is not in canonical form; run scripts/generate-prices.py --format"
                )
            print(f"OK: {len(data['models'])} models, canonical")
            return 0
        if args.format:
            args.prices.write_text(canonical_text(data), encoding="utf-8")
            print(f"Formatted {args.prices.name}")
            return 0

        page = args.page.read_text(encoding="utf-8") if args.page else fetch()
        today = args.today or datetime.datetime.now(datetime.timezone.utc).date().isoformat()
        meta, models, changes, notes = refresh(
            data, parse_table(page), allow_removals=args.allow_removals, today=today
        )
        try:
            reordered = canonical_text(data) != text
        except PricingError:
            reordered = True
        new_text = render(meta, models)
        if new_text != text:
            args.prices.write_text(new_text, encoding="utf-8")
        for change in changes:
            print(change)
        for note in notes:
            print(f"NOTE: {note}")
        print(f"{len(changes)} rate change(s); {args.prices.name} {'updated' if new_text != text else 'unchanged'}")
        if args.body_file:
            args.body_file.write_text(body_markdown(changes, notes, reordered), encoding="utf-8")
        return 0
    except PricingError as exc:
        print(f"Failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
