//! Ask before a command prints a bare, unnamed secret value
//! (cameronsjo/cadence-hooks#776). PreToolUse, `Bash`, **Ask-only**.
//!
//! The backstop for `redact-secret-output`. That hook masks values by the
//! *name* printed beside them, so it is structurally blind to a command whose
//! output is the value alone. This guard covers exactly those producers:
//!
//! - `security find-generic-password|find-internet-password … -w` (macOS
//!   Keychain: prints the password and nothing else);
//! - `kubectl get secret … -o jsonpath|go-template|template|custom-columns`,
//!   `--template`, and `-o json|yaml` piped into `jq`/`yq` (the filter strips
//!   the key names the redactor masks by);
//! - `op read op://…` and `op item get … --reveal` (1Password);
//! - `vault read|kv get -field=…`, `aws secretsmanager get-secret-value`,
//!   `gcloud secrets versions access`, `pass show`.
//!
//! `Ask`, never `Block`: both motivating incidents were legitimate work, and
//! the prompt is its own escape hatch — so no bypass or dismiss exists.
//!
//! **Egress predicate — why this stays quiet on real work.** The top-level
//! pipeline is walked from the producing segment
//! (`split_segments_with_ops_joining_redirects`, so `&>` stays a redirect).
//! The value never reaches the transcript, and the guard says nothing, when:
//! - a segment in the pipeline sends stdout to a file (`> f`, `>> f`, `&> f`,
//!   `1> f`, `>/dev/null`) — not `>&2`, `/dev/stdout`, `/dev/stderr`,
//!   `/dev/tty`, `/dev/fd/*`, `/dev/pts/*` or `/proc/*/fd/*`, which still
//!   reach the terminal. A `tee` anywhere downstream counts as printing,
//!   whatever follows it;
//! - the pipeline's LAST stage is a pure hash (`shasum`, `sha*sum`, `md5sum`,
//!   `md5`, `b2sum`, `cksum`), judged by command word alone.
//!
//! Nothing else counts, by design: counters and quiet greps need flag parsing,
//! and every "consumer that takes the secret on stdin" exemption
//! (`--password-stdin`, `--with-token`) produced bypasses over three review
//! rounds, so `op read … | docker login --password-stdin` asks too.
//!
//! So `kubectl get secret s -o jsonpath='{.data.k}' | base64 -d | shasum` is
//! silent, and the same command without the hash asks.
//!
//! **Deliberately allowed (not asked about):**
//! - a producer inside a script FILE (`bash scripts/x.sh`), which the command
//!   text does not show. Producers inside `$(…)`, backticks, `<(…)`,
//!   `sh -c`/`bash -c` and `eval` ARE judged (core's read-only
//!   `child_scripts`), each against its own pipeline, whatever consumes the
//!   substitution: an argument can be printed by the command itself, a runner
//!   (`sudo echo`, `env … printenv`), `set -x` or a verbose flag, so a
//!   "safe consumer" allow list only generated bypasses and was cut (review
//!   round 4), as was the later login-stdin exemption (round 6);
//! - `echo $(op read … | sha256sum)` asks: core's top-level splitter cuts the
//!   substitution at its inner pipe, so the hash cannot be proven to contain
//!   the value;
//! - `kubectl get secret -o yaml|json`: the output carries key names, which
//!   `redact-secret-output` masks;
//! - `sops -d`: owned by `guard-sops-decrypt` (a hard block);
//! - `op read --out-file|-o <f>`: the value goes to a file.
//!
//! Known accepted gap: `docker inspect -f '{{json .Config}}'` and other
//! producers whose output names its values are left to the redactor.
//!
//! Fails open (ADR-0001): no command means allow.

use cadence_hooks_core::shell::{
    MAX_WRAPPER_DEPTH, child_scripts, command_word, is_redirect_token, peel_command_runners,
    split_segments_with_ops_joining_redirects, strip_group_wrappers, tokenize,
};
use cadence_hooks_core::{Check, CheckResult, HookInput};

/// Asks before a bare secret value is printed to the transcript.
pub struct SecretDumpGuard;

impl Check for SecretDumpGuard {
    fn name(&self) -> &str {
        "guard-secret-dump"
    }

    fn run(&self, input: &HookInput) -> CheckResult {
        let Some(command) = input.command() else {
            return CheckResult::allow();
        };
        match first_exposed_dump(command) {
            Some(producer) => CheckResult::ask(ask_message(producer)),
            None => CheckResult::allow(),
        }
    }
}

fn ask_message(producer: &str) -> String {
    format!(
        "🔑 guard-secret-dump: `{producer}` prints a bare secret value, and nothing in this \
         command keeps it out of the transcript.\n   \
         A value with no name beside it cannot be masked after the fact.\n   \
         To check it without printing it: end the pipeline with `shasum`, or \
         redirect it to a file.\n   \
         Approve if the value only feeds a command that will not print it \
         (`--password-stdin`, an API header), or if it must be shown."
    )
}

/// The label of the first bare-value producer whose stdout reaches the
/// transcript, or `None`.
pub fn first_exposed_dump(command: &str) -> Option<&'static str> {
    exposed_in(command, 0)
}

/// [`first_exposed_dump`] over one script, recursing into every child script
/// the shell runs from a segment — `$(…)`, backticks, `<(…)`, `sh -c`/`bash
/// -c`, `eval` — via core's read-only `child_scripts`, up to
/// `MAX_WRAPPER_DEPTH`. A producer inside a substitution is judged against its
/// own pipeline: `$(op read … | sha256sum)` is contained, `X=$(op read …)`
/// is not.
fn exposed_in(script: &str, depth: usize) -> Option<&'static str> {
    let segments = split_segments_with_ops_joining_redirects(script);
    let argvs: Vec<Vec<String>> = segments
        .iter()
        .map(|(segment, _)| {
            let tokens = tokenize(strip_group_wrappers(segment));
            peel_command_runners(&tokens).to_vec()
        })
        .collect();
    for (i, argv) in argvs.iter().enumerate() {
        if depth < MAX_WRAPPER_DEPTH {
            let stripped = strip_group_wrappers(&segments[i].0);
            let mut children = child_scripts(argv, stripped);
            children.extend(process_substitutions(stripped));
            // Every child is judged, wherever its output goes, with no
            // exceptions: an argument can be printed by the command, a runner,
            // `set -x` or a verbose flag, and each "safe consumer" or "stdin
            // sink" exemption tried here produced bypasses (review rounds 4-6).

            for child in children {
                if let Some(label) = exposed_in(&child, depth + 1) {
                    return Some(label);
                }
            }
        }
        let Some(label) =
            producer(argv).or_else(|| structured_secret_filtered(&segments, &argvs, i))
        else {
            continue;
        };
        if !pipeline_contains_it(&segments, &argvs, i) {
            return Some(label);
        }
    }
    None
}

/// Bodies of `<(…)` / `>(…)` process substitutions in `segment`, which core's
/// `child_scripts` does not return. Outside single quotes only; an unclosed
/// body (the splitter may have cut the segment at a `|` inside it) runs to
/// the end — erring toward judging more, never less.
fn process_substitutions(segment: &str) -> Vec<String> {
    let bytes = segment.as_bytes();
    let mut out = Vec::new();
    let mut in_single = false;
    let mut i = 0;
    while i + 1 < bytes.len() {
        match bytes[i] {
            b'\'' => in_single = !in_single,
            b'<' | b'>' if !in_single && bytes[i + 1] == b'(' => {
                let body_start = i + 2;
                let mut depth = 1;
                let mut j = body_start;
                while j < bytes.len() && depth > 0 {
                    match bytes[j] {
                        b'(' => depth += 1,
                        b')' => depth -= 1,
                        _ => {}
                    }
                    j += 1;
                }
                let body_end = if depth == 0 { j - 1 } else { bytes.len() };
                if let Some(body) = segment.get(body_start..body_end) {
                    out.push(body.to_string());
                }
                i = j;
                continue;
            }
            _ => {}
        }
        i += 1;
    }
    out
}

/// Does the pipeline starting at segment `start` keep the producer's stdout
/// out of the transcript?
fn pipeline_contains_it(
    segments: &[(String, Option<&'static str>)],
    argvs: &[Vec<String>],
    start: usize,
) -> bool {
    let mut i = start;
    loop {
        let argv = &argvs[i];
        // `tee` prints to its own file operands (`/dev/stderr`, `/dev/tty`)
        // as well as down the pipe: whatever follows it, treat it as printing.
        if i > start && argv.first().is_some_and(|w| command_word(w) == "tee") {
            return false;
        }
        if stdout_to_file(argv) {
            return true;
        }
        // A pure hash as the LAST stage: its output is a digest, never the
        // value, and nothing after it can see the value either.
        let last = segments[i].1 != Some("|") || i + 1 >= argvs.len();
        if i > start && last && is_pure_hash(argv) {
            return true;
        }
        if segments[i].1 != Some("|") || i + 1 >= argvs.len() {
            return false;
        }
        i += 1;
    }
}

/// The producer label when `argv` prints a bare secret value.
fn producer(argv: &[String]) -> Option<&'static str> {
    let word = command_word(argv.first()?);
    let rest = &argv[1..];
    match word.as_ref() {
        "security" => {
            let finds = rest
                .iter()
                .any(|t| t == "find-generic-password" || t == "find-internet-password");
            let w_flag = rest.iter().any(|t| {
                t.len() > 1
                    && t.starts_with('-')
                    && !t.starts_with("--")
                    && t[1..].chars().all(|c| c.is_ascii_alphabetic())
                    && t.contains('w')
            });
            (finds && w_flag).then_some("security find-*-password -w")
        }
        "kubectl" => {
            let gets = rest.iter().any(|t| t == "get");
            let secret = rest.iter().any(|t| names_secret_resource(t));
            (gets && secret && bare_output_format(rest)).then_some("kubectl get secret -o jsonpath")
        }
        "op" => {
            // `-o`/`--out-file` keeps the value off the terminal only when the
            // target is a real file, not `/dev/stdout` and friends.
            let to_file = rest.iter().enumerate().any(|(i, t)| {
                let target = if t == "-o" || t == "--out-file" {
                    rest.get(i + 1).map(String::as_str)
                } else {
                    t.strip_prefix("--out-file=")
                };
                target.is_some_and(|f| !f.is_empty() && !is_terminal_path(f))
            });
            // `op read <ref>`: the subcommand is the first non-flag word (an
            // `op://` reference is not required — any read prints a value).
            let reads = (rest
                .iter()
                .find(|t| !t.starts_with('-'))
                .is_some_and(|t| t == "read")
                || (rest.iter().any(|t| t == "read")
                    && rest.iter().any(|t| t.starts_with("op://"))))
                && !to_file;
            let reveals = rest.windows(2).any(|w| w[0] == "item" && w[1] == "get")
                && rest.iter().any(|t| t == "--reveal");
            if reads {
                Some("op read")
            } else if reveals {
                Some("op item get --reveal")
            } else {
                None
            }
        }
        "vault" => {
            let reads = rest.first().is_some_and(|t| t == "read")
                || rest.windows(2).any(|w| w[0] == "kv" && w[1] == "get");
            let field = rest
                .iter()
                .any(|t| t == "-field" || t.starts_with("-field=") || t.starts_with("--field"));
            (reads && field).then_some("vault read -field")
        }
        "aws" => {
            let has = |w: &str| rest.iter().any(|t| t == w);
            if has("secretsmanager") && has("get-secret-value") {
                Some("aws secretsmanager get-secret-value")
            } else if (has("ecr") || has("ecr-public")) && has("get-login-password") {
                Some("aws ecr get-login-password")
            } else if has("ssm")
                && rest.iter().any(|t| t.starts_with("get-parameter"))
                && has("--with-decryption")
            {
                Some("aws ssm get-parameter --with-decryption")
            } else if rest
                .windows(2)
                .any(|w| w[0] == "configure" && w[1] == "get")
                && rest.iter().any(|t| {
                    let t = t.to_ascii_lowercase();
                    t.contains("secret") || t.contains("token") || t.contains("password")
                })
            {
                Some("aws configure get <secret>")
            } else {
                None
            }
        }
        "az" => {
            let has3 = |a: &str, b: &str, c: &str| {
                rest.windows(3).any(|w| w[0] == a && w[1] == b && w[2] == c)
            };
            if has3("keyvault", "secret", "show") {
                Some("az keyvault secret show")
            } else if rest
                .windows(2)
                .any(|w| w[0] == "account" && w[1] == "get-access-token")
            {
                Some("az account get-access-token")
            } else {
                None
            }
        }
        "heroku" => rest
            .iter()
            .any(|t| t == "auth:token")
            .then_some("heroku auth:token"),
        "gopass" => rest
            .iter()
            .find(|t| !t.starts_with('-'))
            .is_some_and(|t| matches!(t.as_str(), "show" | "cat"))
            .then_some("gopass show"),
        "bw" => (rest
            .windows(2)
            .any(|w| w[0] == "get" && matches!(w[1].as_str(), "password" | "totp" | "notes")))
        .then_some("bw get password"),
        "lpass" => (rest.iter().any(|t| t == "show")
            && rest.iter().any(|t| {
                matches!(t.as_str(), "--password" | "--notes") || t.starts_with("--field")
            }))
        .then_some("lpass show --password"),
        "doppler" => (rest.windows(2).any(|w| w[0] == "secrets" && w[1] == "get")
            && rest.iter().any(|t| t == "--plain"))
        .then_some("doppler secrets get --plain"),
        "gcloud" => {
            let access = rest
                .windows(3)
                .any(|w| w[0] == "secrets" && w[1] == "versions" && w[2] == "access");
            let token = rest.iter().any(|t| t == "auth")
                && rest
                    .iter()
                    .any(|t| t == "print-access-token" || t == "print-identity-token");
            if access {
                Some("gcloud secrets versions access")
            } else if token {
                Some("gcloud auth print-access-token")
            } else {
                None
            }
        }
        // `pass show NAME`, and `pass NAME` (shorthand for show); the other
        // subcommands list, edit or manage the store.
        "pass" => rest
            .iter()
            .find(|t| !t.starts_with('-'))
            .is_some_and(|t| !PASS_SUBCOMMANDS.contains(&t.as_str()))
            .then_some("pass show"),
        _ => None,
    }
}

/// `pass` subcommands that do not print a secret.
const PASS_SUBCOMMANDS: &[&str] = &[
    "ls", "list", "find", "search", "grep", "insert", "add", "edit", "generate", "rm", "remove",
    "delete", "mv", "rename", "cp", "copy", "git", "init", "help", "version",
];

/// `kubectl get secret -o json|yaml` piped into `jq`/`yq`: the filter strips
/// the key names the redactor would mask by, so the value comes out bare.
fn structured_secret_filtered(
    segments: &[(String, Option<&'static str>)],
    argvs: &[Vec<String>],
    start: usize,
) -> Option<&'static str> {
    let argv = &argvs[start];
    if argv.first().is_none_or(|w| command_word(w) != "kubectl") {
        return None;
    }
    let rest = &argv[1..];
    let structured = rest.iter().any(|t| t == "get")
        && rest.iter().any(|t| names_secret_resource(t))
        && output_format(rest).is_some_and(|f| f == "json" || f == "yaml");
    if !structured {
        return None;
    }
    let mut i = start;
    while segments[i].1 == Some("|") && i + 1 < argvs.len() {
        i += 1;
        if argvs[i]
            .first()
            .is_some_and(|w| matches!(command_word(w).as_ref(), "jq" | "yq" | "gojq" | "jaq"))
        {
            return Some("kubectl get secret -o json|yaml | jq");
        }
    }
    None
}

/// The `-o`/`--output` value, whichever spelling.
fn output_format(rest: &[String]) -> Option<&str> {
    rest.iter().enumerate().find_map(|(i, t)| {
        if t == "-o" || t == "--output" {
            rest.get(i + 1).map(String::as_str)
        } else if let Some(v) = t.strip_prefix("--output=") {
            Some(v)
        } else {
            t.strip_prefix("-o")
                .map(|v| v.strip_prefix('=').unwrap_or(v))
        }
    })
}

/// `secret`, `secrets`, `secret/<name>`, or a comma list naming one.
fn names_secret_resource(token: &str) -> bool {
    token.split(',').any(|part| {
        let kind = part.split('/').next().unwrap_or(part);
        matches!(kind, "secret" | "secrets")
    })
}

/// An output mode that prints bare field values: `-o jsonpath|go-template|
/// template|custom-columns…` in any spelling, or `--template`.
fn bare_output_format(rest: &[String]) -> bool {
    let is_bare = |value: &str| {
        ["jsonpath", "go-template", "template", "custom-columns"]
            .iter()
            .any(|f| value.starts_with(f))
    };
    output_format(rest).is_some_and(is_bare)
        || rest
            .iter()
            .any(|t| t == "--template" || t.starts_with("--template="))
}

/// Does `argv` redirect its stdout to a file (so nothing reaches the
/// terminal)? Reads each redirect token's descriptor and target.
fn stdout_to_file(argv: &[String]) -> bool {
    let mut i = 0;
    while i < argv.len() {
        let token = &argv[i];
        if !is_redirect_token(token) {
            i += 1;
            continue;
        }
        let both = token.starts_with("&>");
        let body = token.trim_start_matches('&');
        let digits: String = body.chars().take_while(char::is_ascii_digit).collect();
        let after_fd = &body[digits.len()..];
        let is_stdout = both || digits.is_empty() || digits == "1";
        let op_len = after_fd
            .chars()
            .take_while(|c| matches!(c, '>' | '|'))
            .count();
        let writes = after_fd.starts_with('>');
        let glued = &after_fd[op_len..];
        // `>&2`: stdout duplicated onto stderr — still the terminal.
        let dup = glued.starts_with('&');
        let target = if glued.is_empty() {
            i += 1;
            argv.get(i).map(String::as_str).unwrap_or("")
        } else {
            glued
        };
        if is_stdout && writes && !dup && !target.is_empty() && !is_terminal_path(target) {
            return true;
        }
        i += 1;
    }
    false
}

/// A path that is the terminal, not a file: writing there prints.
fn is_terminal_path(target: &str) -> bool {
    matches!(target, "/dev/stdout" | "/dev/stderr" | "/dev/tty")
        || target.starts_with("/dev/fd/")
        || target.starts_with("/dev/pts/")
        || (target.starts_with("/proc/") && target.contains("/fd/"))
}

/// A hash command: its output is a digest of stdin, never stdin itself.
/// Judged by command word alone — no flag parsing to get wrong.
fn is_pure_hash(argv: &[String]) -> bool {
    argv.first().is_some_and(|w| {
        matches!(
            command_word(w).as_ref(),
            "shasum"
                | "sha1sum"
                | "sha224sum"
                | "sha256sum"
                | "sha384sum"
                | "sha512sum"
                | "md5sum"
                | "md5"
                | "b2sum"
                | "cksum"
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exposed_dumps_ask() {
        let cases: &[(&str, &str)] = &[
            (
                "security find-generic-password -s svc -a me -w",
                "security find-*-password -w",
            ),
            (
                "security find-internet-password -s host -w | cat",
                "security find-*-password -w",
            ),
            (
                "sudo security find-generic-password -ws svc",
                "security find-*-password -w",
            ),
            (
                "kubectl get secret app -o jsonpath='{.data.token}' | base64 -d",
                "kubectl get secret -o jsonpath",
            ),
            (
                "kubectl -n prod get secrets/app -ojsonpath={.data.k}",
                "kubectl get secret -o jsonpath",
            ),
            (
                "kubectl get secret app --output=go-template='{{.data.k}}'",
                "kubectl get secret -o jsonpath",
            ),
            (
                "kubectl get secret app --output jsonpath={.data}",
                "kubectl get secret -o jsonpath",
            ),
            ("op read op://vault/item/password", "op read"),
            ("op read 'op://vault/item/password' >&2", "op read"),
            ("op read op://v/i/f > /dev/stdout", "op read"),
            (
                "op item get db --fields password --reveal",
                "op item get --reveal",
            ),
            (
                "echo start; security find-generic-password -s x -w && echo done",
                "security find-*-password -w",
            ),
            // A sink before the producer does not protect it.
            ("echo x | shasum; op read op://v/i/f", "op read"),
            // grep that prints matching lines is not a sink.
            ("op read op://v/i/f | grep -i abc", "op read"),
            // Gate 2 (#776 review): tee and terminal paths print.
            (
                "security find-generic-password -s svc -w | tee /dev/stderr | sha256sum",
                "security find-*-password -w",
            ),
            (
                "security find-generic-password -s svc -w | tee x | docker login --password-stdin",
                "security find-*-password -w",
            ),
            (
                "security find-generic-password -s svc -w > /proc/self/fd/1",
                "security find-*-password -w",
            ),
            (
                "security find-generic-password -s svc -w >/dev/fd/1",
                "security find-*-password -w",
            ),
            ("op read op://v/i/f -o /dev/stdout", "op read"),
            ("op read op://v/i/f --out-file /dev/stdout", "op read"),
            ("op read op://v/i/f --out-file=/dev/stdout", "op read"),
            ("op read op://v/i/f -o /dev/stderr", "op read"),
            // Gate 2: more bare-value producers.
            (
                "kubectl get secret s --template='{{.data.p}}'",
                "kubectl get secret -o jsonpath",
            ),
            (
                "kubectl get secret s -o custom-columns=P:.data.p",
                "kubectl get secret -o jsonpath",
            ),
            (
                "kubectl get secret s -o json | jq -r .data.p | base64 -d",
                "kubectl get secret -o json|yaml | jq",
            ),
            (
                "kubectl get secret s -o yaml | yq .data.p",
                "kubectl get secret -o json|yaml | jq",
            ),
            ("vault kv get -field=password secret/x", "vault read -field"),
            ("vault read -field=value secret/x", "vault read -field"),
            (
                "aws secretsmanager get-secret-value --secret-id x --query SecretString --output text",
                "aws secretsmanager get-secret-value",
            ),
            (
                "gcloud secrets versions access latest --secret=x",
                "gcloud secrets versions access",
            ),
            ("pass show x", "pass show"),
            // Round 2: producers inside substitutions and wrappers.
            ("echo $(op read op://v/i/f)", "op read"),
            (
                "echo \"$(kubectl get secret s -o jsonpath={.data.p} | base64 -d)\"",
                "kubectl get secret -o jsonpath",
            ),
            ("echo `pass show x`", "pass show"),
            ("sh -c 'pass show x'", "pass show"),
            ("bash -c 'op read op://v/i/f'", "op read"),
            ("eval 'vault kv get -field=p secret/x'", "vault read -field"),
            (
                "X=$(security find-generic-password -s svc -w); echo $X",
                "security find-*-password -w",
            ),
            ("cat <(pass show x)", "pass show"),
            ("cat <<< \"$(op read op://v/i/f)\"", "op read"),
            // Round 6: no stdin-sink or counter exemptions at all.
            (
                "docker login --password-stdin <<< \"$(op read op://v/i/f)\"",
                "op read",
            ),
            (
                "gh auth login --with-token <<< \"$(op read op://v/i/t)\"",
                "op read",
            ),
            (
                "gh auth login --with-token < <(op read op://v/i/f)",
                "op read",
            ),
            (
                "security find-generic-password -s svc -w | docker login -u me --password-stdin",
                "security find-*-password -w",
            ),
            (
                "op read op://v/i/token | gh auth login --with-token",
                "op read",
            ),
            ("op read op://v/i/f | grep -q expected", "op read"),
            ("op read op://v/i/f | openssl dgst -sha256", "op read"),
            (
                "kubectl get secret app -o jsonpath='{.data.token}' | wc -c",
                "kubectl get secret -o jsonpath",
            ),
            ("op read op://v/i/f | sha256sum | cat", "op read"),
            (
                "docker run -i --rm alpine sh -c cat login --password-stdin <<< \"$(op read op://v/i/p)\"",
                "op read",
            ),
            (
                "docker run -i --rm alpine sh -c cat login --password-stdin < <(op read op://v/i/p)",
                "op read",
            ),
            (
                "docker run -i --rm --name login alpine tee /dev/stderr --password-stdin <<< \"$(op read op://v/i/p)\"",
                "op read",
            ),
            (
                "docker login -u \"$(op read p)\" --password-stdin r <<< \"$(op read p)\"",
                "op read",
            ),
            (
                "gh auth login --with-token --hostname \"$(op read p)\" <<< \"$(op read p)\"",
                "op read",
            ),
            // Round 5: the stdin sink needs a real login command, and only
            // its here-string is exempt.
            (
                "echo \"$(op read op://v/i/p)\" --password-stdin <<< x",
                "op read",
            ),
            ("cat --with-token <<< \"$(op read op://v/i/p)\"", "op read"),
            (
                "tee /dev/stderr --password-stdin <<< \"$(op read op://v/i/p)\"",
                "op read",
            ),
            ("cat <(op read op://v/i/p) --with-token", "op read"),
            (
                "docker login -u \"$(op read op://v/i/u)\" --password-stdin r <<< \"$(op read op://v/i/p)\"",
                "op read",
            ),
            // Round 5 producers.
            (
                "gcloud auth print-access-token",
                "gcloud auth print-access-token",
            ),
            (
                "gcloud auth application-default print-access-token",
                "gcloud auth print-access-token",
            ),
            ("heroku auth:token", "heroku auth:token"),
            (
                "aws configure get aws_secret_access_key",
                "aws configure get <secret>",
            ),
            (
                "aws ecr get-login-password --region x",
                "aws ecr get-login-password",
            ),
            (
                "aws ssm get-parameter --name /x --with-decryption",
                "aws ssm get-parameter --with-decryption",
            ),
            (
                "az keyvault secret show --vault-name v -n x",
                "az keyvault secret show",
            ),
            ("az account get-access-token", "az account get-access-token"),
            ("pass db", "pass show"),
            ("gopass show db", "gopass show"),
            ("bw get password item", "bw get password"),
            ("lpass show --password item", "lpass show --password"),
            ("printf \"%s\\n\" \"$(op read x)\"", "op read"),
            ("docker run -e T=\"$(op read x)\" alpine env", "op read"),
            // Round 4: every nested producer asks, whatever consumes it.
            ("TOKEN=$(op read op://v/i/f) gh api user", "op read"),
            (
                "curl -H \"Authorization: Bearer $(op read op://v/i/f)\" https://x",
                "op read",
            ),
            ("psql \"postgres://u:$(pass show db)@h/db\"", "pass show"),
            ("sudo echo \"$(op read op://v/i/f)\"", "op read"),
            ("env T=\"$(op read op://v/i/f)\" printenv T", "op read"),
            ("ssh h \"echo $(op read op://v/i/f)\"", "op read"),
            ("python3 -c 'print(1)' \"$(pass show x)\"", "pass show"),
            ("set -x; mysql -p\"$(pass show db)\"", "pass show"),
            (
                "curl -v -H \"X-Api-Key: $(pass show k)\" https://api",
                "pass show",
            ),
            // The top-level splitter cuts `$(… | …)` at its inner pipe, so a
            // hash inside a substitution cannot be proven to contain the
            // value: ask rather than guess.
            ("echo $(op read op://v/i/f | sha256sum)", "op read"),
        ];
        for (command, want) in cases {
            assert_eq!(first_exposed_dump(command), Some(*want), "{command}");
        }
    }

    #[test]
    fn contained_or_unrelated_commands_stay_silent() {
        let cases: &[&str] = &[
            "kubectl get secret app -o jsonpath='{.data.token}' | base64 -d | shasum",
            "security find-generic-password -s svc -w | sha256sum",
            "security find-generic-password -s svc -w > /tmp/pw",
            "security find-generic-password -s svc -w >/dev/null",
            "security find-generic-password -s svc -w &>/dev/null",
            "op read --out-file /tmp/f op://v/i/f",
            "op read -o /tmp/f op://v/i/f",
            "aws configure get region",
            "aws ssm get-parameter --name /x",
            "pass ls",
            "pass",
            "kubectl get secret s -o json | jq -r .data.p | base64 -d | sha256sum",
            "vault kv get secret/x",
            "pass ls",
            // Output names its values: the redactor's job.
            "kubectl get secret app -o yaml",
            "kubectl get secret app -o json",
            "kubectl get pods -o jsonpath='{.items[*].metadata.name}'",
            // Not a -w read.
            "security find-generic-password -s svc",
            "op item get db --fields username",
            "op item list",
            // Prose, not a command.
            "echo 'security find-generic-password -w'",
            "git commit -m 'op read op://x'",
            "",
        ];
        for command in cases {
            assert_eq!(first_exposed_dump(command), None, "{command}");
        }
    }

    #[test]
    fn check_asks_with_message() {
        let input = HookInput::from_json(
            r#"{"tool_name":"Bash","tool_input":{"command":"op read op://v/i/f"}}"#,
        )
        .unwrap();
        let result = SecretDumpGuard.run(&input);
        assert_eq!(result.outcome, cadence_hooks_core::Outcome::Ask);
        assert!(result.message.unwrap().contains("op read"));

        let quiet =
            HookInput::from_json(r#"{"tool_name":"Bash","tool_input":{"command":"ls"}}"#).unwrap();
        assert_eq!(
            SecretDumpGuard.run(&quiet).outcome,
            cadence_hooks_core::Outcome::Allow
        );
    }

    /// Round 6: an unclosed `<<<$(` flood (the removed here-string scan was
    /// quadratic on it; a timeout fails open). 1 MB, release bound 0.5 s.
    #[test]
    fn unclosed_here_string_flood_stays_fast() {
        let flood = format!(
            "docker login --password-stdin r {}",
            "<<<$( ".repeat(1_000_000 / 6)
        );
        let bound = if cfg!(debug_assertions) {
            std::time::Duration::from_secs(20)
        } else {
            std::time::Duration::from_millis(500)
        };
        let started = std::time::Instant::now();
        let _ = first_exposed_dump(&flood);
        assert!(started.elapsed() < bound, "took {:?}", started.elapsed());
    }

    #[test]
    fn adversarial_200kb_command_stays_fast() {
        let long = format!("op read op://v/i/f{}", " | cat".repeat(40_000));
        let started = std::time::Instant::now();
        assert_eq!(first_exposed_dump(&long), Some("op read"));
        assert!(started.elapsed() < std::time::Duration::from_secs(5));
    }
}
